### PR TITLE
aleena commit

### PR DESCRIPTION
**Pull request by aleenaazeem**
I have added a contributor.md file as it was stated on the hacktober website. Other than that i have added my profile in it.

### CODE REVIEW

**Comment by ashish-gopalika** [comment]
@aleenaazeem remove the part after # from your profile both after name and tech stack.

**Comment by aleenaazeem** [comment]
okay

**Comment by aleenaazeem** [comment]
Made changed

**Comment by ashish-gopalika** [comment]
@aleenaazeem it's still there in the last line after tech_stack

**Comment by aleenaazeem** [comment]
Okay I'll fix it

**Comment by aleenaazeem** [comment]
updated

**Pull request merged**
