### PR TITLE
Added my profile

### PR DESCRIPTION
**Pull request by BEAST-PRINCE**

### CODE REVIEW

**Comment by HarshitGulgulia** [comment]
The name should be exactly the same as in your GitHub profile.
The letter casing should also match.

**Comment by BEAST-PRINCE** [comment]
I've updated my branch.
Please check if it matches your requirements.

**Comment by BEAST-PRINCE** [comment]
> The name should be exactly the same as in your GitHub profile. The letter casing should also match.
Updated

**Comment by HarshitGulgulia** [comment]
There should be a comma(,) after first two lines

**Comment by BEAST-PRINCE** [comment]
> There should be a comma(,) after first and second line

Updated. 
:)

**Comment by HarshitGulgulia** [comment]
The folder name should be BEAST-PRINCE and file name should be BEAST-PRINCE.md
Please make a new PR

**Pull request merged**
